#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

process='gnocchi-statsd'
bind_port=$(get_config_val /etc/gnocchi/gnocchi.conf statsd port 8125)

if ! healthcheck_listen $process $bind_port; then
    echo "There is no $process process listening on ports $bind_port in the container."
    exit 1
fi
