#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

check_url=$(get_url_from_vhost /etc/httpd/conf.d/10-keystone_wsgi.conf)
healthcheck_curl ${check_url}
