#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

process='neutron-sriov-nic-agent'
args="${@:-5671 5672}"

if healthcheck_port $process $args; then
    exit 0
else
    ports=${args// /,}
    echo "There is no $process process connected via RabbitMQ ports ($ports) running in the container"
    exit 1
fi
