#!/bin/bash

# Copyright (C) 2017   Robin Cernin (rcernin@redhat.com)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Load all necessary functions
source ${DIR}/load_functions

# Unset all variables that might be possibly set.
DIRECTORY=
DISCOVERED_NODE=
VERSION=
TARGET_HOSTNAME=
PCS_DIRECTORY=
VERSION_CHECK=
PLUGIN=

# Set display filters
verbose_good=0
verbose_bad=0
verbose_warn=0

while :; do
    case $1 in
        -h|-\?|--help)
            show_help
            exit
            ;;
        -f|--file)
            if [ -n "$2" ]; then
                DIRECTORY=$2
                shift
            else
                bad '"--file" requires a non-empty option argument.' >&2
                exit 1
            fi
            ;;
        --file=?*)
            DIRECTORY=${1#*=}
            ;;
        --file=)
            bad '"--file" requires a non-empty option argument.' >&2
            exit 1
            ;;
        -v|--verbose)
            set -x
            ;;
        -p|--plugin)
            if [ -n "$2" ]; then
                PLUGIN=$2
                shift
            else
                bad '"--plugin" requires a non-empty option argument.' >&2
                exit 1
            fi
            ;;
        -d|--display)
            if [ -n "$2" ]; then
                FILTER=$2
                shift
            else
                bad '"--display" requires a non-empty option argument.' >&2
                exit 1
            fi
            ;;
        --)
            shift
            break
            ;;
        -?*)
            bad "Unknown option: ${1}" >&2
            exit 1
            ;;
        *)
            break
    esac

    shift
done

if [ ! -d "${DIRECTORY}" ]
then
  bad "Uh, oh, ${DIRECTORY} is not directory."
  exit 1
fi

show_logo

# Here we are going to set the display filter we want.
# By default all filters are on unless specified explicitly.

FILTER="$(echo ${FILTER} | tr ',' ' ')"
if [ -z "${FILTER}" ]
then 
  # All filters are on if no filter was specified.
  verbose_warn=1
  verbose_good=1
  verbose_bad=1
fi

if [ -n "${FILTER}" ]
then
  for filter in ${FILTER}
  do
    match_filter ${filter} "warn good bad"
    if [[ "${FOUND}" -eq 1 ]] && [[ ${filter} = "good" ]]
    then
      verbose_good=1
    elif [[ "${FOUND}" -eq 1 ]] && [[ ${filter} = "bad" ]]
    then
      verbose_bad=1
    elif [[ "${FOUND}" -eq 1 ]] && [[ ${filter} = "warn" ]]
    then
      verbose_warn=1
    fi
  done
fi

TARGET_HOSTNAME="$(cat ${DIRECTORY}/hostname)"
echo "SOSreport was created at $(cat ${DIRECTORY}/date)"
echo "Hostname: ${TARGET_HOSTNAME}"

PYTHON="/usr/bin/python"
TMPFILE="$(mktemp /tmp/cittelus-script.XXXXXX)"
# Check if we are running openstack plugin if empty by default to openstack
get_version

PLUGIN="$(echo ${PLUGIN} | tr ',' ' ')"
if [ -n "${PLUGIN}" ]
then
  for plugin in ${PLUGIN}
  do
    match_filter "./plugins/${plugin}" "./plugins/*"
    if [[ "${FOUND}" -eq "1" ]]
    then
      if [ "${plugin}" = "openstack" ]
	then
	  discover_node
	  print_version
      fi
      for FILE in ./plugins/"${plugin}"/*
      do
        [ -f "${FILE}" ] || continue
        EXTENSION=${FILE##*.}
	if [ "${plugin}" = "openstack" ]
	  then
           if grep -q "^REFOSP_VERSION=.*${VERSION}.*$" "${FILE}" && grep -q "^REFNODE_TYPE=.*${DISCOVERED_NODE}.*$" "${FILE}"
           then
	     case ${EXTENSION} in
	       sh) 
                   run_sh
                   ;;
	       py) ${PYTHON} ${FILE} ${DIRECTORY} ;;
	       *) echo "File: ${FILE}. Usupported format." ;;
	     esac
           fi
         else
           case ${EXTENSION} in
             sh)
                 run_sh
                 ;;
             py) ${PYTHON} ${FILE} ${DIRECTORY} ;;
             *) echo "File: ${FILE}. Usupported format." ;;
           esac
         fi
      done
    fi
  done
fi
