#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

conf=/etc/swift/container-server.conf
cache=/var/cache/swift/container.recon

if ps -e | grep --quiet swift-container-server; then
    if ! crudini --get $conf pipeline:main pipeline | grep -q healthcheck; then
        echo "healthcheck is not available" >&2
        exit 0
    fi

    # swift-container-server is still eventlet
    bind_host=$(wrap_ipv6 $(get_config_val $conf DEFAULT bind_ip 127.0.0.1))
    bind_port=$(get_config_val $conf DEFAULT bind_port 6001)
    healthcheck_curl http://${bind_host}:${bind_port}/healthcheck
fi
