#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

if pgrep -f swift-proxy-server; then
    conf=/etc/swift/proxy-server.conf

    if ! crudini --get $conf pipeline:main pipeline | grep -q healthcheck; then
        echo "healthcheck is not available" >&2
        exit 0
    fi

    # swift-proxy is still eventlet
    bind_host=$(wrap_ipv6 $(get_config_val $conf DEFAULT bind_ip 127.0.0.1))
    bind_port=$(get_config_val $conf DEFAULT bind_port 8080)
    healthcheck_curl http://${bind_host}:${bind_port}/healthcheck
fi
