#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

bind_host=$(wrap_ipv6 $(get_config_val /etc/tacker/tacker.conf DEFAULT bind_host 127.0.0.1))
bind_port=$(get_config_val /etc/tacker/tacker.conf DEFAULT bind_port 9890)

healthcheck_curl http://${bind_host}:${bind_port}/
