#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh


if ps -e | grep --quiet nova-api-metada; then
    bind_host=$(get_config_val /etc/nova/nova.conf DEFAULT metadata_listen 127.0.0.1)
    bind_port=$(get_config_val /etc/nova/nova.conf DEFAULT metadata_listen_port 8775)
    check_url="http://${bind_host}:${bind_port}/"
else
    check_url=$(get_url_from_vhost /etc/httpd/conf.d/10-nova_api_wsgi.conf)
fi

healthcheck_curl ${check_url}
