#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

process='rsync'
args="${@:-873}"

if healthcheck_listen $process $args; then
    exit 0
else
    ports=${args// /,}
    echo "There is no $process process, listening on port(s) $ports, running in the container."
    exit 1
fi
