#!/bin/sh

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

conf=/etc/swift/object-server.conf

if ! crudini --get $conf pipeline:main pipeline | grep -q healthcheck; then
	echo "healthcheck is not available" >&2
	exit 0
fi

# swift-object-server is still eventlet
bind_host=$(get_config_val $conf DEFAULT bind_ip 127.0.0.1)
bind_port=$(get_config_val $conf DEFAULT bind_port 6000)
# Add brackets if IPv6
if [[ $bind_host =~ ":" ]]; then
  bind_host="[${bind_host}]"
fi
healthcheck_curl http://${bind_host}:${bind_port}/healthcheck
